apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetazrk8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetapiazr-app
  template:
    metadata:
      labels:
        app: dotnetapiazr-app
    spec:
      containers:
      - name: mydotnetdockerrepo
        image: sample1container.azurecr.io/neethucleetus/api:#{Build.BuildId}#
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapiazr-appmetadata
spec:
  selector:
    app: dotnetapiazr-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
